name: release
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'image tag prefix'
        default: 'rc'
        required: true

jobs:
  push-container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prepare
        id: prep
        run: |
          VERSION="${{ github.event.inputs.tag }}-${GITHUB_SHA::8}"
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF/refs\/tags\//}
          fi
          echo ::set-output name=BUILD_DATE::$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          echo ::set-output name=VERSION::${VERSION}
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: fo808
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: stefanprodan
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Push image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/fo808/forcing:${{ steps.prep.outputs.VERSION }}
            ghcr.io/fo808/forcing:latest
            docker.io/fo808/forcing:${{ steps.prep.outputs.VERSION }}
            docker.io/fo808/forcing:latest
          labels: |
            org.opencontainers.image.title=${{ github.event.repository.name }}
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.revision=${{ github.sha }}
